### ISSUE TITLE
Running marginalized_prediction 

### ISSUE THREAD

**Issue by jtuyls** [automl/random_forest_run#15]
I tried to use the marginalized_prediction method of the pyrfr in SMAC. However I get following error when calling marginalized_prediction:

<img width="1319" alt="screen shot 2017-04-26 at 09 57 12" src="https://cloud.githubusercontent.com/assets/17315610/25424085/5785c27c-2a67-11e7-86d0-4c6700a32dc1.png">

Also, if I try to run the pyrfr_test_partitioning.py file to check if the example works, I get another error:

<img width="593" alt="screen shot 2017-04-26 at 09 58 33" src="https://cloud.githubusercontent.com/assets/17315610/25424132/8956b5f4-2a67-11e7-9c1e-fb962509c17d.png">

I am using python 3.6 on MAC OS X in an anaconda environment with gcc 4.8.5.
Running pyrfr_example.py works just fine.

**Comment by sfalkner** [comment]
That issue arises when I forget to update the tests and examples to reflect changes in the code ... Sorry about that. I will keep this open for now to remind me to fix that soon.
