### ISSUE TITLE
Building pyrfr on circle-ci fails

### ISSUE THREAD

**Issue by mfeurer** [automl/random_forest_run#17]
In order to build the SMAC documentation online on circle-ci, I need to install the pyrfr. For reasons I don't understand, this fails. There's probably just a dependency missing or in a wrong version, but I don't know how to figure this out.

Here are some links which might be helpful:

[Failing build](https://circleci.com/gh/automl/SMAC3/467?utm_campaign=build-failed&utm_content=failing-command&utm_medium=email#tests/containers/0/actions/19)

[circle.yml](https://github.com/automl/SMAC3/blob/development/circle.yml)

**Comment by sfalkner** [comment]
As the build on Travis is fine, I suspect that the setup of the environment on CircleCI is the problem. The error indicates that SWIG fails, and I remember that I needed to install SWIG3 and tell cmake about it (see .travis.yml file). I don't know how this should be handled within pip.

**Comment by mfeurer** [comment]
Thanks, I'll go for an Anaconda installation than. Seems to give me the least trouble....
