### ISSUE TITLE
Errors when installing the pyrfr from pypi

### ISSUE THREAD

**Issue by mfeurer** [automl/random_forest_run#19]
The installation itself does not fail, but the installation process prints two error messages as shown in this github issue: https://github.com/automl/auto-sklearn/issues/275

**Comment by mitar** [comment]
I can confirm. I a simple Docker image I am trying to install it, I get the following error:

    Running setup.py bdist_wheel for pyrfr ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4pbvvsgk/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpbs679xmapip-wheel- --python-tag cp35:
    running bdist_wheel
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.5
    creating build/lib.linux-x86_64-3.5/pyrfr
    copying pyrfr/__init__.py -> build/lib.linux-x86_64-3.5/pyrfr
    running build_ext
    building '_regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/pyrfr
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/usr/include/python3.5m -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-3.5/pyrfr/regression_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pyrfr/regression_wrap.o -o build/lib.linux-x86_64-3.5/_regression.cpython-35m-x86_64-linux-gnu.so
    building '_util' extension
    swigging pyrfr/util.i to pyrfr/util_wrap.cpp
    swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/util_wrap.cpp pyrfr/util.i
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/usr/include/python3.5m -c pyrfr/util_wrap.cpp -o build/temp.linux-x86_64-3.5/pyrfr/util_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option '-Wstrict-prototypes' is valid for C/ObjC but not for C++
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pyrfr/util_wrap.o -o build/lib.linux-x86_64-3.5/_util.cpython-35m-x86_64-linux-gnu.so
    installing to build/bdist.linux-x86_64/wheel
    running install
    running install_lib
    creating build/bdist.linux-x86_64
    creating build/bdist.linux-x86_64/wheel
    creating build/bdist.linux-x86_64/wheel/pyrfr
    copying build/lib.linux-x86_64-3.5/pyrfr/__init__.py -> build/bdist.linux-x86_64/wheel/pyrfr
    copying build/lib.linux-x86_64-3.5/_util.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
    copying build/lib.linux-x86_64-3.5/_regression.cpython-35m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel
    running install_egg_info
    running egg_info
    writing dependency_links to pyrfr.egg-info/dependency_links.txt
    writing pyrfr.egg-info/PKG-INFO
    writing top-level names to pyrfr.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pyrfr.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.pxd' under directory 'pyrfr'
    warning: no files found matching '*.pyx' under directory 'pyrfr'
    warning: manifest_maker: MANIFEST.in, line 11: unknown action 'CMakeList.txt'
    
    writing manifest file 'pyrfr.egg-info/SOURCES.txt'
    Copying pyrfr.egg-info to build/bdist.linux-x86_64/wheel/pyrfr-0.4.0.egg-info
    running install_scripts
    Checking .pth file support in build/bdist.linux-x86_64/wheel/
    /usr/bin/python3 -E -c pass
    TEST FAILED: build/bdist.linux-x86_64/wheel/ does NOT support .pth files
    error: bad install directory or PYTHONPATH
    
    You are attempting to install a package to a directory that is not
    on PYTHONPATH and which Python does not read ".pth" files from.  The
    installation directory you specified (via --install-dir, --prefix, or
    the distutils default setting) was:
    
        build/bdist.linux-x86_64/wheel/
    
    and your PYTHONPATH environment variable currently contains:
    
        ''
    
    Here are some of your options for correcting the problem:
    
    * You can choose a different installation directory, i.e., one that is
      on PYTHONPATH or supports .pth files
    
    * You can add the installation directory to the PYTHONPATH environment
      variable.  (It must then also be on PYTHONPATH whenever you run
      Python and want to use the package(s) you are installing.)
    
    * You can set up the installation directory to support ".pth" files by
      using one of the approaches described here:
    
      https://pythonhosted.org/setuptools/easy_install.html#custom-installation-locations
    
    Please make the appropriate changes for your system and try again.
    
    ----------------------------------------
    Failed building wheel for pyrfr

Maybe the issue is that I have `python3-wheel` installed and it is trying to build a wheel to cache the installation and it fails then?

**Comment by sfalkner** [comment]
I will close that for now. Please reopen if that issue still exists.

**Comment by petrtsatsin** [comment]
I still see this bug. Can you guys address this somehow?

**Comment by tlind** [comment]
Same issue here!

**Comment by sfalkner** [comment]
The installation is fine, it's just that building the wheel fails for some reason. If somebody knows where this problems originates, or can point me at least in the right direction, I would be more than happy to fix it, but I have no idea where it comes from and how to solve it.

**Comment by drpoggi** [comment]
I stumbled on this issue because I was getting the same error on an internal work project. Turns out the common link between this package and our package is calling `self.do_egg_install()` in the custom install command in `setup.py`. If you remove that, the wheel should build just find.

I haven't figured out a solution yet for keeping the custom install command and being able to build wheels, but thought it might be helpful to point out where it's coming from.

**Comment by sfalkner** [comment]
Thank you so much  @drpoggi ! I was actually able to fix it ( commit: f975f947979cd1bc46eca30833f8267c2f71514c) by looking into distutils itself and call its legacy method!

**Comment by drpoggi** [comment]
Awesome! Glad I could help @sfalkner, and thanks for sharing your fix!

**Comment by minusdavid** [comment]
I've had this same issue when trying to build RPM packages from Loris (https://github.com/loris-imageserver/loris) and this solution worked for me! 

No idea why it works but interesting that it works!
