### ISSUE TITLE
unit_test_fanova fails on macos

### ISSUE THREAD

**Issue by wskish** [automl/random_forest_run#22]
: Test command: /Users/wsk/random_forest_run/build/tests/ut_fanova "/Users/wsk/random_forest_run/test_data_sets/"
5: Test timeout computed to be: 9.99988e+06
5: Boost.Test WARNING: token "/Users/wsk/random_forest_run/test_data_sets/" does not correspond to the Boost.Test argument 
5:                     and should be placed after all Boost.Test arguments and the -- separator.
5:                     For example: ut_fanova --random -- /Users/wsk/random_forest_run/test_data_sets/
5: Running 1 test case...
5: /Users/wsk/random_forest_run/tests/unit_test_fanova.cpp:269: fatal error: in "legacy_fanova_test": difference{0.00697191} between the_tree.get_subspace_size(1){177.37526839097126} and s1{178.61191331472548} exceeds 1e-06%
5: 
5: *** 1 failure is detected in the test module "ut_fanova"
5/8 Test #5: ut_fanova ........................***Failed    0.01 sec

**Comment by sfalkner** [comment]
Thanks for filing the issue and sorry for the late response.
Unfortunately, I am not able to reproduce this. The same unit test passes locally on my machine(s) and on TravisCI.
If you could provide a bit more info about your setup (OS, versions of Boost, etc...), maybe we can figure it out.
