### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by aaronkl** [automl/random_forest_run#23]
Installing the current master branch fails with the following error message:

~$ pip install git+https://github.com/automl/random_forest_run.git
Collecting git+https://github.com/automl/random_forest_run.git
  Cloning https://github.com/automl/random_forest_run.git to /tmp/pip-2mqes4u9-build
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... error
    Complete output from command /home/kleinaa/virtualenv/debug/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-2mqes4u9-build/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-s574epp1-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/kleinaa/virtualenv/debug/include/site/python3.5/pyrfr:
    /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/setuptools/dist.py:350: UserWarning: The version specified ('${RFR_VERSION_MAJOR}.${RFR_VERSION_MINOR}') is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
      "details." % self.metadata.version
    running install
    running build_ext
    building '_regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build
    creating build/temp.linux-x86_64-3.5
    creating build/temp.linux-x86_64-3.5/pyrfr
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/usr/include/python3.5m -I/home/kleinaa/virtualenv/debug/include/python3.5m -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-3.5/pyrfr/regression_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from pyrfr/regression_wrap.cpp:3168:0:
    ./include/rfr/data_containers/default_data_container_with_instances.hpp: In instantiation of ‘void rfr::data_containers::default_container_with_instances<num_t, response_t, index_t>::check_consistency() [with num_t = double; response_t = double; index_t = unsigned int]’:
    pyrfr/regression_wrap.cpp:18885:33:   required from here
    ./include/rfr/data_containers/default_data_container_with_instances.hpp:216:11: warning: unused variable ‘t’ [-Wunused-variable]
       index_t t = get_type_of_response();
               ^
    creating build/lib.linux-x86_64-3.5
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pyrfr/regression_wrap.o -o build/lib.linux-x86_64-3.5/_regression.cpython-35m-x86_64-linux-gnu.so
    building '_util' extension
    swigging pyrfr/util.i to pyrfr/util_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/util_wrap.cpp pyrfr/util.i
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I${CMAKE_SOURCE_DIR}/include -I./include -I/usr/include/python3.5m -I/home/kleinaa/virtualenv/debug/include/python3.5m -c pyrfr/util_wrap.cpp -o build/temp.linux-x86_64-3.5/pyrfr/util_wrap.o -O2 -std=c++11
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    x86_64-linux-gnu-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.5/pyrfr/util_wrap.o -o build/lib.linux-x86_64-3.5/_util.cpython-35m-x86_64-linux-gnu.so
    running install_lib
    running build_py
    creating build/lib.linux-x86_64-3.5/pyrfr
    copying pyrfr/util.py -> build/lib.linux-x86_64-3.5/pyrfr
    copying pyrfr/__init__.py -> build/lib.linux-x86_64-3.5/pyrfr
    copying pyrfr/regression.py -> build/lib.linux-x86_64-3.5/pyrfr
    copying pyrfr/docstrings.i -> build/lib.linux-x86_64-3.5/pyrfr
    copying build/lib.linux-x86_64-3.5/_util.cpython-35m-x86_64-linux-gnu.so -> /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages
    copying build/lib.linux-x86_64-3.5/_regression.cpython-35m-x86_64-linux-gnu.so -> /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages
    creating /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/pyrfr
    copying build/lib.linux-x86_64-3.5/pyrfr/util.py -> /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/pyrfr
    copying build/lib.linux-x86_64-3.5/pyrfr/__init__.py -> /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/pyrfr
    copying build/lib.linux-x86_64-3.5/pyrfr/docstrings.i -> /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/pyrfr
    copying build/lib.linux-x86_64-3.5/pyrfr/regression.py -> /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/pyrfr
    byte-compiling /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/pyrfr/util.py to util.cpython-35.pyc
    byte-compiling /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/pyrfr/__init__.py to __init__.cpython-35.pyc
    byte-compiling /home/kleinaa/virtualenv/debug/lib/python3.5/site-packages/pyrfr/regression.py to regression.cpython-35.pyc
    running install_data
    error: can't copy 'include': doesn't exist or not a regular file

It seems that this is due to the latest commit

**Comment by sfalkner** [comment]
sorry forgot to push the latest commit here
