### ISSUE TITLE
Readme.md / RTD disagree

### ISSUE THREAD

**Issue by KEggensperger** [automl/random_forest_run#26]
When trying to install pyrfr from source I noticed that the installation guides in Readme.md and RTD disagree. And it is unclear which one to use.

Also, there is probably a `cd ..` missing in the installation in Readme.md before `python setup.py install --user` and one would want to use `git clone ...` instead of `git checkout ...`

**Comment by KEggensperger** [comment]
When following the Readme.md installation `cmake ..` fails with the following. I assume it is because it requires the BOOST libraries although I do not want to compile the unittests?

```
-- The CXX compiler identification is GNU 4.8.5
-- Check for working CXX compiler: /home/eggenspk/miniconda3/envs/TESTRFR/bin/c++
-- Check for working CXX compiler: /home/eggenspk/miniconda3/envs/TESTRFR/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_unit_test_framework

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  CMakeLists.txt:20 (find_package)


-- Found Doxygen: /usr/bin/doxygen (found version "1.8.11") 
-- Found PythonInterp: /home/eggenspk/miniconda3/envs/TESTRFR/bin/python3 (found suitable version "3.5.3", minimum required is "3") 
-- Found SWIG: /usr/bin/swig3.0 (found version "3.0.8") 
Skipping unit_test_classification_forest.cpp
-- Configuring incomplete, errors occurred!
See also "/home/eggenspk/TEST/random_forest_run/build/CMakeFiles/CMakeOutput.log".
```

**Comment by sfalkner** [comment]
The RTD is gone, as it referred to ancient version hosted on Bitbucket. I didn't even remember that this was still online.
I will fix the dependency for building the python module, but I plan to change the way you can install the python bindings (too much hassle to keep everything in sync, it will be PyPi only at some point). Installing it via
```
pip install pyrfr
```
will compile from source. There is no difference to cloning the repo and building it from there at this point.
