### ISSUE TITLE
stdc++ header files installed in /usr/local/include ?

### ISSUE THREAD

**Issue by musamarcusso** [automl/random_forest_run#27]
Hello,

I recently updated SMAC3 and random_forest_run. I cloned it from GitHub and the installation itself went fine. Only that I noticed that some headers were installed in my /usr/local/include and suddenly my other projects started to show compilation errors. Here are some examples:

/usr/local/include/inttypes.h:58:4: error: ‘intmax_t’ does not name a type
    intmax_t quot;
    ^
/usr/local/include/inttypes.h:59:4: error: ‘intmax_t’ does not name a type
    intmax_t rem;
    ^
/usr/local/include/inttypes.h:288:1: error: ‘_inline’ does not name a type
 _inline

I solved this issue by renaming the /usr/local/include to /usr/local/include.old to see if that was the culprit and for now everything works again. I tested installing SMAC3 and random_forest_run in another machine and the same problem happened.
Is something being installed in this include folder by this package? And if it is, is it supposed to be installed like that? 

Best,
Musa

**Comment by sfalkner** [comment]
Hey Musa,
thanks for trying our software.

How exactly did you install the 'pyrfr' package? The official way is to simply run
```
pip install pyrfr
```
What you describe sounds more like you ran ```cmake``` and a ```make install``` which is what you would want if you were interested in the actual C++ headers (which you are probably not).
Hope that helps.

Best,
Stefan

**Comment by musamarcusso** [comment]
Hello Stefan,

I tried to install it with `pip` but I get this message

```
Could not find .egg-info directory in install record for pyrfr>=0.5.0 from https://pypi.python.org/packages/29/26/483591f369e9b030497dc5eee9a9b3a90ee4668b449159d396f7758e6c3c/pyrfr-0.5.tar.gz#md5=97b8fdfde20386cee9ed2000c4f9ec53 (from -r requirements.txt (line 10))
```

Then I installed it from source. In the end I installed it with `cmake` again but then installed it only locally for my user and the problem didn't come up again. Is there a problem with the package in `pip`?
Best,
Musa

**Comment by sfalkner** [comment]
Hey Musa,
I updated the pip package two days ago, the current version number is 0.5.1 which installs fine here on my local machine. The error you posted indicates that you call pip on some requirements file, what package is that from?
Best,
Stefan

**Comment by musamarcusso** [comment]
Hi Stefan, thanks for the information, I will try it out. It is a requirement from SMAC3, I was recently updating the package to use pSMAC.

**Comment by sfalkner** [comment]
Should be fixed in the latest version.
