### ISSUE TITLE
SWIG wheel building failed due to syntax error with SWIG 2.0

### ISSUE THREAD

**Issue by engelen** [automl/random_forest_run#31]
I'm in the process of getting a clean setup of `auto-sklearn` running on CentOS, and I'm getting an error building the wheel. I know there's quite a few issues about this already, but I've found the cause for at least one of the errors, which is the `./include/rfr/trees/binary_fanova_tree.hpp:329: Error: Syntax error in input(3)`. It has been encountered by other users before, see, e.g., https://github.com/automl/random_forest_run/issues/21, https://github.com/automl/auto-sklearn/issues/314, https://github.com/automl/random_forest_run/issues/18.

It appears to happen in older versions of SWIG, which don't have all support required for C++11 and later versions. Either way, the error is as follows (solution can be found below):

```
running install
running build_ext
building '_regression' extension
swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
swig -python -c++ -I${CMAKE_SOURCE_DIR}/include -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
./include/rfr/trees/binary_fanova_tree.hpp:329: Error: Syntax error in input(3).
error: command 'swig' failed with exit status 1
```

As the message suggests, this is a problem with line 329 of https://github.com/automl/random_forest_run/blob/v0.6.0/include/rfr/trees/binary_fanova_tree.hpp#L329. Apparently, SWIG has some trouble handling the `>>&`: changing it to `> >&` solves the problem.

**For users encountering this problem:**
Use SWIG >= 3.0. That will also solve the syntax error.

**Comment by sfalkner** [comment]
Should be fixed via 0a793e0.
