### ISSUE TITLE
After cmake .. and make, there is no make install for this package.  What is going on?

### ISSUE THREAD

**Issue by shyamalschandra** [automl/random_forest_run#38]
I am getting the following output:

```
Shyamals-iMac:build testuser$ sudo make install
make: *** No rule to make target `install'.  Stop.
```

What should I do or what needs to be changed to install pyrfr on my machine?

**Comment by sfalkner** [comment]
Please use
```
pip install pyrfr
```
to install the python bindings. The package provided there is up to date with the master branch.
If you have any trouble with that, please let me know.
