### ISSUE TITLE
Install fails in both python2 and python3

### ISSUE THREAD

**Issue by echo66** [automl/random_forest_run#41]
Greetings!

I'm trying to install pyrfr but I'm getting a gcc related error. My gcc version is:

**gcc (GCC) 7.2.1 20170915 (Red Hat 7.2.1-2)**

When I run pip3 install --user pyrfr, I get the following output:

Collecting pyrfr
  Using cached pyrfr-0.7.3.tar.gz
Installing collected packages: pyrfr
  Running setup.py install for pyrfr ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6jy9xu7f/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-txdrnv1a-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build_ext
    building 'pyrfr._regression' extension
    swigging pyrfr/regression.i to pyrfr/regression_wrap.cpp
    swig -python -c++ -modern -features nondynamic -I./include -o pyrfr/regression_wrap.cpp pyrfr/regression.i
    creating build
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/pyrfr
    gcc -pthread -Wno-unused-result -Wsign-compare -DDYNAMIC_ANNOTATIONS_ENABLED=1 -DNDEBUG -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv -fPIC -I./include -I/usr/include/python3.6m -c pyrfr/regression_wrap.cpp -o build/temp.linux-x86_64-3.6/pyrfr/regression_wrap.o -O2 -std=c++11
    gcc: error trying to exec 'cc1plus': execvp: No such file or directory
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-6jy9xu7f/pyrfr/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-txdrnv1a-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-6jy9xu7f/pyrfr/

I get a similar errror with python2.

**Comment by sfalkner** [comment]
[This SO question](https://stackoverflow.com/questions/8878676/compile-error-g-error-trying-to-exec-cc1plus-execvp-no-such-file-or-dir) suggests that you are missing a c++ compiler. Not sure which package manager RH is using, but the link above should contain the answer. Please try some of the answers there. If it works, could you please get back to me or close the issue yourself?
Thanks!

**Comment by echo66** [comment]
Solved after reading the SO answer.
