### ISSUE TITLE
Provide a Conda package and pip wheel

### ISSUE THREAD

**Issue by KOLANICH** [automl/random_forest_run#48]

**Comment by dhirschfeld** [comment]
***xref:*** https://github.com/conda-forge/staged-recipes/pull/13919

**Comment by BastianZim** [comment]
Conda package has been made available at https://anaconda.org/conda-forge/pyrfr

**Comment by mfeurer** [comment]
And wheels are there as well, too: https://pypi.org/project/pyrfr/0.8.1/#files
