### ISSUE TITLE
Please provide an *official* license

### ISSUE THREAD

**Issue by dhirschfeld** [automl/random_forest_run#54]
:wave: As a dependency of `auto-sklearn` I'm trying to help package `pyrfr` with `conda`:
https://github.com/conda-forge/staged-recipes/pull/13919

Not having a *proper* license can be problematic if you want others to actually be able to use your work as implied below:
https://github.com/automl/random_forest_run/blob/e51ab097120c25b7a637e48c6cae16351b8db0c5/pyrfr/setup.py#L47

IANAL but I believe that if you don't have a license that laws in certain countries confer copyright or other rights as the authors whether or not you want them.

Whilst the current license implies that others are free to use the software, it's not an official, recognised license so it's unclear whether or not it would hold up in court. Because of this lack of legal clarity the software would not be allowed to be used in many enterprises.

If you do want anyone and everyone to be able to use your software I'd suggest using a license such as [`MIT`](https://spdx.org/licenses/MIT.html) which is very commonly used in the PyData stack.

**Comment by dhirschfeld** [comment]
ping @sfalkner, @AndreBiedenkapp, @mfeurer would you be happy to relicense as `MIT`? If so, I'm happy to put in a PR to do so...

**Comment by BastianZim** [comment]
@mlindauer Maybe you could also weight in as one of the heads of this project? It would just be about the type of license, we'd be happy to then create the PR, thanks!

**Comment by mlindauer** [comment]
Hi Bastian and Dave,

Thanks for your interest in auto-sklearn.
I fully agree that we should have a proper license for our pyrfr package. I'm in contact with the other authors of the package and I hope that we will have a solution soon.

Most of the time, we go for a BSD or Apache license. Is there a special reason why you suggest to use MIT?

Best,
Marius

**Comment by dhirschfeld** [comment]
> Most of the time, we go for a BSD or Apache license. Is there a special reason why you suggest to use MIT?

No special reason. Either of those are fine as well.

**Comment by mfeurer** [comment]
We're happy re-license under BSD3. I just created a PR under #55, please let us know whether that's what's required?

**Comment by BastianZim** [comment]
Yes, that's perfect, thank you very much! Just to confirm that is [BSD 3-Clause "New" or "Revised" License](https://spdx.org/licenses/BSD-3-Clause.html), correct?

**Comment by mfeurer** [comment]
Most likely, I took this one https://opensource.org/licenses/BSD-3-Clause (Sorry, I don't know what the New or Revised means)

**Comment by BastianZim** [comment]
I just needed the SPDX short identifier, that's fine, thank you!

**Comment by BastianZim** [comment]
Hi everybody,

I just wanted to check in and ask if you already had some time to evaluate publishing the new version with the license? From what I can see in #56 you're working on publishing everything to pip but if it's easier we can easily go with GitHub releases. It's only two lines of code that need to be changed in the conda recipe and we can change it back later as well, so that wouldn't be a problem at all for us. 
Would just be nice to have pyrfr because it's a dependency for a couple other automl recipes that are blocked until this is released. 
Thanks!

**Comment by mfeurer** [comment]
Sorry @BastianZim, I didn't see the github notification that @franchuterivera did almost everything already last week :( I have two more questions on this and then we can merge and hopefully have it this week. Sorry for the delay.

**Comment by BastianZim** [comment]
No worries at all, thanks for the update!

**Comment by mfeurer** [comment]
Fixed by #55
