### ISSUE TITLE
Swig 4.0 nondynamic support causing Segmentation fault

### ISSUE THREAD

**Issue by franchuterivera** [automl/random_forest_run#57]
# Problem Statement
Random Forest run requires nondynamic support in two places

- Interface to swig [here](https://github.com/automl/random_forest_run/blob/316c4d9f57f93710d306ec2e8235198c43deccf7/pyrfr/pyrfr/regression.i#L3).
- And in the setup.py [here](https://github.com/automl/random_forest_run/blob/316c4d9f57f93710d306ec2e8235198c43deccf7/pyrfr/setup.py#L37).

Which causes the following segmentation fault:
```
# To make this trace one can install apt install python3-dbg gdb
# Have this dummy file
# cat reproduce.py 
#     import pyrfr.regression as reg
#     data = reg.default_data_container(64)
# 
# and run gdb -ex r --args python3 reproduce.py
(gdb) backtrace 
#0  0x00000000005cec00 in PyDict_SetItem (op=op@entry=0x0, key='this', 
    value=value@entry=<SwigPyObject at remote 0x7f9bd68cd180>) at ../Objects/dictobject.c:1526
#1  0x00007f9bd66ecf6f in SWIG_Python_SetSwigThis (
    swig_this=<SwigPyObject at remote 0x7f9bd68cd180>, inst=<optimized out>)
    at pyrfr/regression_wrap.cpp:1979
#2  SWIG_Python_InitShadowInstance (args=<optimized out>) at pyrfr/regression_wrap.cpp:2309

```

# Next Steps
This appears to be a problem with our usage of nondynamic support as tracked [here](https://github.com/swig/swig/issues/1955).

**Comment by mfeurer** [comment]
Fixed by #61
